# -*- coding: utf-8 -*-
"""ALFIDO_Customer_Behavior_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUftVefPFQ1ASaPZbv7EnQ3ZOAQ1T_i_

# Customer Behavior Analysis

This notebook analyzes customer transactions and behavior to identify segments, purchase patterns, and potential churn indicators. It covers data loading, cleaning, feature engineering, clustering for segmentation, visualization, and business recommendations.
"""

# Step 1: Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

print("Libraries imported successfully.")

# Step 2: Load Dataset

# Using an embedded sample dataset as the external file was not found previously.
# In a real scenario, you would replace this with: df = pd.read_csv("your_customer_data.csv")
csv_data = """CustomerID,Quantity,Price,OtherColumn
1,5,10.0,A
2,3,20.0,B
1,2,10.0,A
3,8,5.0,C
2,1,20.0,B
4,7,12.5,D
5,4,15.0,E
4,1,12.5,D
"""
df = pd.read_csv(io.StringIO(csv_data))

print("Dataset Shape:", df.shape)
print("First 5 rows of the dataset:")
display(df.head())

# Step 3: Data Cleaning

print("\nMissing Values before cleaning:")
print(df.isnull().sum())

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Fill numeric missing values with the median
numeric_cols = df.select_dtypes(include=np.number).columns
for col in numeric_cols:
    df[col].fillna(df[col].median(), inplace=True)

# Fill categorical missing values with the mode
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

print("\nData Cleaning Completed. Missing Values after cleaning:")
print(df.isnull().sum())

# Step 4: Basic Dataset Information

print("\nDataset Information:")
df.info()
print("\nDescriptive Statistics:")
display(df.describe())

# Step 5: Feature Engineering

# Calculate Total Spending per transaction
if 'Quantity' in df.columns and 'Price' in df.columns:
    df['Total_Spending'] = df['Quantity'] * df['Price']
    print(" 'Total_Spending' feature created.")
else:
    print(" 'Quantity' or 'Price' columns not found for 'Total_Spending' feature.")

# Calculate Purchase Frequency for each CustomerID
if 'CustomerID' in df.columns:
    purchase_frequency = df.groupby('CustomerID').size()
    df['Purchase_Frequency'] = df['CustomerID'].map(purchase_frequency)
    print(" 'Purchase_Frequency' feature created.")
else:
    print(" 'CustomerID' column not found for 'Purchase_Frequency' feature.")

print("\nFirst 5 rows with new features:")
display(df.head())

# Step 6: Customer Segmentation (K-Means Clustering)

# Ensure 'CustomerID' exists and aggregate data for segmentation
if 'CustomerID' in df.columns and 'Total_Spending' in df.columns and 'Purchase_Frequency' in df.columns:
    customer_data = df.groupby('CustomerID').agg({
        'Total_Spending':'sum', # Sum of total spending per customer
        'Purchase_Frequency':'mean' # Mean of purchase frequency (since it's already per customer in df)
    }).reset_index()

    # Standardize the features for K-Means
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(customer_data[['Total_Spending','Purchase_Frequency']])

    # Apply K-Means clustering
    # Choosing n_clusters=3 for a reasonable number of segments for demonstration
    kmeans = KMeans(n_clusters=3, random_state=42, n_init=10) # n_init added for robust centroid initialization
    customer_data['Cluster'] = kmeans.fit_predict(scaled_data)

    print("Customer segmentation completed. First 5 rows of customer data with clusters:")
    display(customer_data.head())
else:
    print("Required columns for segmentation (CustomerID, Total_Spending, Purchase_Frequency) not found.")

# Step 7: Customer Segment Visualization

if 'Cluster' in customer_data.columns:
    plt.figure(figsize=(8,5))
    sns.countplot(
        x='Cluster',
        data=customer_data,
        palette='viridis'
    )
    plt.title("Distribution of Customer Segments")
    plt.xlabel("Customer Cluster")
    plt.ylabel("Number of Customers")
    plt.show()
else:
    print("No 'Cluster' column found for visualization. Please ensure segmentation was successful.")

# Step 8: Total Spending Distribution

if 'Total_Spending' in customer_data.columns:
    plt.figure(figsize=(8,5))
    sns.histplot(
        customer_data['Total_Spending'],
        bins=10, # Adjusted bins for smaller dataset
        kde=True
    )
    plt.title("Customer Spending Distribution (Aggregated)")
    plt.xlabel("Total Spending")
    plt.ylabel("Frequency")
    plt.show()
else:
    print("No 'Total_Spending' column found for visualization. Please ensure feature engineering was successful.")

# Step 9: Purchase Frequency Analysis by Segment

if 'Cluster' in customer_data.columns and 'Purchase_Frequency' in customer_data.columns:
    plt.figure(figsize=(8,5))
    sns.boxplot(
        x='Cluster',
        y='Purchase_Frequency',
        data=customer_data,
        palette='coolwarm'
    )
    plt.title("Purchase Frequency by Customer Segment")
    plt.xlabel("Customer Cluster")
    plt.ylabel("Purchase Frequency")
    plt.show()
else:
    print("Required columns for Purchase Frequency analysis (Cluster, Purchase_Frequency) not found.")

# Step 10: Cluster Profile

if 'Cluster' in customer_data.columns:
    cluster_summary = customer_data.groupby('Cluster').agg({
        'Total_Spending':['mean','sum'],
        'Purchase_Frequency':'mean'
    })

    print("\nCluster Summary:")
    display(cluster_summary)
else:
    print("No 'Cluster' column found for cluster profiling. Please ensure segmentation was successful.")

"""## Step 11: Business Recommendations

Based on the cluster analysis, here are some general recommendations:

1.  **High-Value Customers (e.g., Cluster 0 based on summary):** Reward with loyalty programs, exclusive offers, and personalized communication to maintain retention.
2.  **Medium-Value Customers (e.g., Cluster 1):** Encourage increased spending through targeted promotions, product recommendations, and upselling opportunities.
3.  **Lower-Value Customers (e.g., Cluster 2):** Implement re-engagement campaigns, special discounts, or feedback surveys to understand their needs and prevent churn.
4.  **Personalization:** Use insights from each segment to tailor marketing messages and product offerings.
5.  **Churn Prevention:** Monitor behavior changes within segments that might indicate a risk of churn and intervene proactively.
"""

# Step 12: Export Results

# Export the customer data with assigned clusters to a CSV file
if 'Cluster' in customer_data.columns:
    customer_data.to_csv(
        "Customer_Segments_Output.csv",
        index=False
    )
    print("\nCustomer segments exported to 'Customer_Segments_Output.csv'")
else:
    print("No 'Cluster' column found for export. Please ensure segmentation was successful.")

print("\nAnalysis workflow completed!")